# Generated by Django 5.2.6 on 2025-10-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_payment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID único del webhook (ej: payment_123 o merchant_order_456)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        help_text="Tipo: payment, merchant_order, etc.", max_length=50
                    ),
                ),
                (
                    "mp_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del pago de MercadoPago",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "preference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de preferencia de MercadoPago",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(help_text="Payload completo recibido del webhook"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si se procesó exitosamente",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Número de intentos de procesamiento"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Máximo de reintentos antes de marcar como fallido",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Último error encontrado", null=True
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, help_text="Detalles completos del error", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Cuándo se recibió el webhook"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se procesó exitosamente",
                        null=True,
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Cuándo debe intentarse el próximo reintento",
                        null=True,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pago relacionado (puede ser null si aún no se creó)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Webhook",
                "verbose_name_plural": "Eventos de Webhook",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "processed"],
                        name="payments_we_status_260223_idx",
                    ),
                    models.Index(
                        fields=["next_retry_at"], name="payments_we_next_re_545f9c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_we_created_ef8db8_idx"
                    ),
                ],
            },
        ),
    ]
