name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests & Code Quality
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verificar formato de código
      run: black --check --diff .
      
    - name: Verificar orden de imports
      run: isort --check-only --diff .
      
    - name: Linting
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
    - name: Verificación Django
      run: |
        python manage.py check
        python manage.py makemigrations --check --dry-run
        
    - name: Ejecutar pruebas
      run: pytest --cov=. --cov-report=xml
      
    - name: Subir cobertura
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
